os:
# ordered slow to fast
- windows
- osx
- linux
language: node_js
node_js:
- '8'
branches:
  only:
  - master
  # npm version tags
  - /^v\d+\.\d+\.\d+$/
env:
- DEBUG=ember-cli-test-server
before_script:
- npm run lint
