os:
- osx
- linux
language: node_js
node_js:
- '8'
branches:
  only:
  - master
  # npm version tags
  - /^v\d+\.\d+\.\d+$/
env:
- DEBUG=ember-cli-test-server
before_script:
- npm run lint
jobs:
  include:
  - os: windows
    script: npm test -- --retries=1

